Updated ci.yml to have a 'v2' of code coverage action, which is more robust, is skipped when prior steps are skipped, and uses env vars instead of hard-coding

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -272,28 +272,40 @@ jobs:
   ## Merge and upload code coverage report files once all tests are done
   ##
   ## Runs when:
-  ##   - always (unless workflow is cancelled)
+  ##   - always (unless workflow is cancelled OR any tests are skipped)
   trigger-code-coverage-report:
-    if: ${{ always() && !cancelled() }}
-    name: Upload Code Coverage Report
+    if: ${{ always() && !cancelled() && !contains(needs.*.result, 'skipped') }}
+    name: Merge & Upload Code Coverage Report
     runs-on: ubuntu-latest
     needs:
       - stacks-core-tests
       - bitcoin-tests
       - p2p-tests
       - epoch-tests
+    env:
+      REPORT_FILES_DIR: "code_coverage_files"
+      REPORT_FILES_EXT: "info"
     steps:
-      # Checkout the code (Coveralls requires source code to be available when action is called)
-      - name: Checkout the latest code
-        id: git_checkout
-        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
       # Download the code coverage .info files generated by tests from artifacts (prefixed by commit SHA)
       - name: Download code coverage artifacts
         uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c # 8.0.1
         with:
-          pattern: ${{ github.sha }}-*.info
-          path: code_coverage_files
+          pattern: ${{ github.sha }}-*.${{ env.REPORT_FILES_EXT }}
+          path: ${{ env.REPORT_FILES_DIR }}
           merge-multiple: true
+      # Check for at least 1 code coverage files
+      - name: Check for at least 1 code coverage file
+        shell: bash
+        run: |
+          file_count=$(find . -type f -wholename "./${{ env.REPORT_FILES_DIR }}/*.${{ env.REPORT_FILES_EXT }}" | wc -l)
+          if [ "$file_count" -eq 0 ]; then
+            echo "ERROR: no code coverage files found to merge. Verify that they were correctly generated and uploaded in prior CI steps"
+            exit 1
+          fi
+      # Checkout the code (Coveralls requires source code to be available when action is called)
+      - name: Checkout the latest code
+        id: git_checkout
+        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
       # Install lcov for merging the reports
       - name: Install lcov
         shell: bash
@@ -303,13 +315,12 @@ jobs:
       - name: Merge code coverage files
         shell: bash
         run: |
-          cd code_coverage_files && \
-          find . -name "*.info" | awk '{print "-a", $0}' | xargs lcov -o code-coverage-report.info
+          cd ${{ env.REPORT_FILES_DIR }} && \
+          find . -name "*.${{ env.REPORT_FILES_EXT }}" | awk '{print "-a", $0}' | xargs lcov -o code-coverage-report.${{ env.REPORT_FILES_EXT }}
       # Upload the merged code coverage file to Coveralls
       - name: Upload code coverage to Coveralls
         uses: coverallsapp/github-action@648a8eb78e6d50909eff900e4ec85cab4524a45b # v2.3.6
         with:
-          file: code_coverage_files/code-coverage-report.info
+          file: ${{ env.REPORT_FILES_DIR }}/code-coverage-report.${{ env.REPORT_FILES_EXT }}
           compare-ref: ${{ github.base_ref }} # defaults to master if this isn't supplied
           fail-on-error: true
-      
