CI changes to speedup testing times

diff --git a/.github/workflows/stacks-blockchain-tests.yml b/.github/workflows/stacks-blockchain-tests.yml
--- a/.github/workflows/stacks-blockchain-tests.yml
+++ b/.github/workflows/stacks-blockchain-tests.yml
@@ -1,95 +1,288 @@
-##
-## Run tests for tagged releases
-##
+## Github workflow to run full genesis and unit tests
 
-name: Tests
-
-# Only run when:
-#   - manually triggered via the ci.yml workflow
+name: Tests::Stacks Blockchain
 
 on:
   workflow_call:
 
+defaults:
+  run:
+    shell: bash
+
+env:
+  BITCOIND_TEST: 1
+  RUST_BACKTRACE: full
+  SEGMENT_DOWNLOAD_TIMEOUT_MINS: 15
+
+concurrency:
+  group: stacks-blockchain-tests-${{ github.workflow }}-${{ github.ref }}
+  # Only cancel in progress if this is for a PR
+  cancel-in-progress: ${{ github.event_name == 'pull_request' }}
+
 jobs:
-  # Run full genesis test
+  # Full genesis test with code coverage
   full-genesis:
     name: Full Genesis Test
     runs-on: ubuntu-latest
+    ## run a maximum of 2 concurrent tests from the test matrix
+    strategy:
+      fail-fast: false
+      max-parallel: 2
+      matrix:
+        test-name:
+          - neon_integrations::bitcoind_integration_test
     steps:
+      ## Checkout the code
       - name: Checkout the latest code
         id: git_checkout
-        uses: actions/checkout@v3
-      - name: Single full genesis integration test
-        id: full_genesis_test
-        env:
-          DOCKER_BUILDKIT: 1
-        # Remove .dockerignore file so codecov has access to git info
-        run: |
-          rm .dockerignore
-          docker build -o coverage-output -f ./.github/actions/bitcoin-int-tests/Dockerfile.large-genesis .
-      - name: Large Genesis Codecov
-        id: full_genesis_codecov
-        uses: codecov/codecov-action@v3
-        with:
-          files: ./coverage-output/lcov.info
-          name: large_genesis
-          fail_ci_if_error: false
+        uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3.5.3
 
-  # Run unit tests with code coverage
+      ## Install rust toolchain (llvm-tools-preview)
+      - name: Setup Rust Toolchain
+        id: setup_rust_toolchain
+        uses: actions-rust-lang/setup-rust-toolchain@f3c84ee10bf5a86e7a5d607d487bf17d57670965 # v1.5.0
+        with:
+          toolchain: stable
+          components: llvm-tools-preview
+          cache: false
+
+      ## Restore cargo cache data
+      - name: Restore Cargo Cache
+        id: restore_cargo_cache
+        uses: actions/cache/restore@88522ab9f39a2ea568f7027eddc7d8d8bc9d59c8 # v3.3.1
+        with:
+          fail-on-cache-miss: true
+          path: |
+            ~/.cargo/bin/
+            ~/.cargo/registry/index/
+            ~/.cargo/registry/cache/
+            ~/.cargo/git/db/
+          # key: ${{ github.event.repository.name }}-cargo
+          key: ${{ github.event.repository.name }}-${{ github.sha }}-cargo
+
+      ## Restore bitcoin cache data
+      - name: Restore Bitcoin Binary Cache
+        id: restore_bitcoin_cache
+        uses: actions/cache/restore@88522ab9f39a2ea568f7027eddc7d8d8bc9d59c8 # v3.3.1
+        with:
+          fail-on-cache-miss: true
+          path: /tmp/bitcoin
+          key: ${{ github.event.repository.name }}-bitcoin-binaries
+
+      ## Restore genesis nextest archive cache data
+      - name: Restore Genesis Archive Cache
+        id: restore_test-archive_cache
+        uses: actions/cache/restore@88522ab9f39a2ea568f7027eddc7d8d8bc9d59c8 # v3.3.1
+        with:
+          fail-on-cache-miss: true
+          path: /tmp/genesis_archive.tar.zst
+          # key: ${{ github.event.repository.name }}-genesis-archive
+          key: ${{ github.event.repository.name }}-${{ github.sha }}-genesis-archive
+
+      ## Restore nextest target cache data
+      - name: Restore Target Cache
+        id: restore_target_cache
+        uses: actions/cache/restore@88522ab9f39a2ea568f7027eddc7d8d8bc9d59c8 # v3.3.1
+        with:
+          fail-on-cache-miss: true
+          path: ./target
+          # key: ${{ github.event.repository.name }}-target
+          key: ${{ github.event.repository.name }}-${{ github.sha }}-target
+
+      ## Symlink bitoind to $PATH
+      - name: Link Bitcoin Binary
+        id: bitcoin_binary
+        run: |
+          sudo ln -s /tmp/bitcoin/bin/bitcoind /bin/
+          ls -al /bin/bitcoind
+
+      ## Run test matrix using cached archive file
+      - name: Run Tests
+        id: run_tests
+        run: |
+          cargo nextest run \
+            --test-threads 1 \
+            --run-ignored all \
+            --retries 2 \
+            --final-status-level fail \
+            --archive-file /tmp/genesis_archive.tar.zst \
+            "${{ matrix.test-name }}"
+
+      ## Generate code coverage using grcov
+      - name: Run grcov
+        id: run_grcov
+        run: |
+          grcov . --binary-path ./target/debug/ -s . -t lcov --branch --ignore-not-existing --ignore "/*" -o lcov.info
+          echo "created=true\n" >> $GITHUB_OUTPUT
+
+      ## Upload coverage to codecov
+      ##   - use wretry action, to retry on a failed upload 3x
+      - name: Upload Code Coverage
+        id: code_coverage
+        uses: Wandalen/wretry.action@a163f62ae554a8f3cbe27b23db15b60c0ae2e93c # v1.3.0
+        with:
+          action: codecov/codecov-action@eaaf4bedf32dbdc6b720b63067d99c4d77d6047d # v3.1.4
+          with: |
+            files: ./lcov.info
+            name: large_genesis
+            fail_ci_if_error: false
+            verbose: true
+          attempt_limit: 3
+          attempt_delay: 10000
+
+  # unit tests with code coverage
   unit-tests:
     name: Unit Tests
     runs-on: ubuntu-latest
+    ## partition the tests in 8 shards
+    strategy:
+      matrix:
+        partition: [1, 2, 3, 4, 5, 6, 7, 8] # partition the tests into 8 jobs
     steps:
+      ## checkout the code
       - name: Checkout the latest code
         id: git_checkout
-        uses: actions/checkout@v3
-      - name: Run unit tests (with coverage)
-        id: unit_tests_codecov
-        env:
-          DOCKER_BUILDKIT: 1
-        # Remove .dockerignore file so codecov has access to git info
-        run: |
-          rm .dockerignore
-          docker build -o coverage-output -f ./.github/actions/bitcoin-int-tests/Dockerfile.code-cov .
-      - name: Run unit tests
-        id: codedov
-        uses: codecov/codecov-action@v3
+        uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3.5.3
+
+      ## install rust toolchain
+      - name: Setup Rust Toolchain
+        id: setup_rust_toolchain
+        uses: actions-rust-lang/setup-rust-toolchain@f3c84ee10bf5a86e7a5d607d487bf17d57670965 # v1.5.0
         with:
-          files: ./coverage-output/lcov.info
-          name: unit_tests
-          fail_ci_if_error: false
+          toolchain: stable
+          components: llvm-tools-preview
+          cache: false
+
+      ## Restore cargo cache data
+      - name: Restore Cargo Cache
+        id: restore_cargo_cache
+        uses: actions/cache/restore@88522ab9f39a2ea568f7027eddc7d8d8bc9d59c8 # v3.3.1
+        with:
+          fail-on-cache-miss: true
+          path: |
+            ~/.cargo/bin/
+            ~/.cargo/registry/index/
+            ~/.cargo/registry/cache/
+            ~/.cargo/git/db/
+          # key: ${{ github.event.repository.name }}-cargo
+          key: ${{ github.event.repository.name }}-${{ github.sha }}-cargo
+
+      ## Restore bitcoin cache data
+      - name: Restore Bitcoin Binary Cache
+        id: restore_bitcoin_cache
+        uses: actions/cache/restore@88522ab9f39a2ea568f7027eddc7d8d8bc9d59c8 # v3.3.1
+        with:
+          fail-on-cache-miss: true
+          path: /tmp/bitcoin
+          key: ${{ github.event.repository.name }}-bitcoin-binaries
+
+      ## Restore test archive cache data
+      - name: Restore Test Archive Cache
+        id: restore_test-archive_cache
+        uses: actions/cache/restore@88522ab9f39a2ea568f7027eddc7d8d8bc9d59c8 # v3.3.1
+        with:
+          fail-on-cache-miss: true
+          path: /tmp/test_archive.tar.zst
+          # key: ${{ github.event.repository.name }}-test-archive
+          key: ${{ github.event.repository.name }}-${{ github.sha }}-test-archive
+
+      ## Restore target cache data
+      - name: Restore Target Cache
+        id: restore_target_cache
+        uses: actions/cache/restore@88522ab9f39a2ea568f7027eddc7d8d8bc9d59c8 # v3.3.1
+        with:
+          fail-on-cache-miss: true
+          path: ./target
+          # key: ${{ github.event.repository.name }}-target
+          key: ${{ github.event.repository.name }}-${{ github.sha }}-target
+
+      ## Symlink bitoind to $PATH
+      - name: Link Bitcoin Binary
+        id: bitcoin_binary
+        run: |
+          sudo ln -s /tmp/bitcoin/bin/bitcoind /bin/
+          ls -al /bin/bitcoind
+
+      ## Run test shards using cached archive file (defined as matrix.partition)
+      ##   - timeout after 30 minutes
+      - name: Run Tests
+        id: run_tests
+        timeout-minutes: 30
+        run: |
+          cargo nextest run \
+            --test-threads num-cpus \
+            --retries 2 \
+            --final-status-level fail \
+            --fail-fast \
+            --archive-file /tmp/test_archive.tar.zst \
+            --partition count:${{ matrix.partition }}/8
+
+      ## Generate code coverage using grcov
+      - name: Run grcov
+        if: inputs.tag != ''
+        id: run_grcov
+        run: |
+          grcov . --binary-path ./target/debug/ -s . -t lcov --branch --ignore-not-existing --ignore "/*" -o lcov.info
+          echo "created=true\n" >> $GITHUB_OUTPUT
+
+      ## Upload coverage to codecov
+      ##   - use wretry action, to retry on a failed upload 3x
+      - name: Upload Code Coverage
+        id: code_coverage
+        uses: Wandalen/wretry.action@a163f62ae554a8f3cbe27b23db15b60c0ae2e93c # v1.3.0
+        with:
+          action: codecov/codecov-action@eaaf4bedf32dbdc6b720b63067d99c4d77d6047d # v3.1.4
+          with: |
+            files: ./lcov.info
+            name: unit_tests
+            fail_ci_if_error: false
+            verbose: true
+          attempt_limit: 3
+          attempt_delay: 10000
 
   open-api-validation:
     name: OpenAPI Validation
     runs-on: ubuntu-latest
     steps:
+      ## checkout the code
       - name: Checkout the latest code
         id: git_checkout
-        uses: actions/checkout@v3
-      - name: Run units tests (with coverage)
-        id: api_codecov
-        env:
-          DOCKER_BUILDKIT: 1
-        run: docker build -o dist/ -f .github/actions/open-api/Dockerfile.open-api-validate .
+        uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3.5.3
+
+      ## Use redoc to generate HTML of openapi.yml
+      - name: Redoc
+        id: run_redoc
+        uses: seeebiii/redoc-cli-github-action@c9649b33918da5eb290b81cd03a943caea091540 # v10
+        with:
+          args: "bundle -o ./open-api-docs.html ./docs/rpc/openapi.yaml"
+
+      ## Test the resultant html
+      - name: check result
+        id: check_redoc
+        run: |
+          test -f ./open-api-docs.html || (echo "Missing ./open-api-docs.html from previous step." && exit 1)
+
+      ## Upload the html file artifact
       - name: Upload bundled html
         id: upload_html_artifact
-        uses: actions/upload-artifact@v3
+        uses: actions/upload-artifact@0b7f8abb1508181956e8e162db84b466c27e18ce # v3.1.2
         with:
           name: open-api-bundle
           path: |
-            dist
+            ./open-api-docs.html
 
-  # Run net-tests
+  ## Disabled
+  ##   - this test can take several hours to run
   nettest:
-    # disable this job/test for now, since we haven't seen this pass
-    #  on github actions in a while, and the failures can take > 4 hours
     if: ${{ false }}
     name: Net-Test
     runs-on: ubuntu-latest
     steps:
+      ## checkout the code
       - name: Checkout the latest code
         id: git_checkout
-        uses: actions/checkout@v3
+        uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3.5.3
+
       - name: Run network relay tests
         id: nettest
         env:
@@ -101,17 +294,28 @@ jobs:
     name: Core Contracts Test
     runs-on: ubuntu-latest
     steps:
+      ## checkout the code
       - name: Checkout the latest code
         id: git_checkout
-        uses: actions/checkout@v3
+        uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3.5.3
+
+      ## Use Clarinet to run contract unit-tests
       - name: Execute core contract unit tests in Clarinet
         id: clarinet_unit_test
-        uses: docker://hirosystems/clarinet:1.1.0
+        uses: docker://hirosystems/clarinet:latest
         with:
           args: test --coverage --manifest-path=./contrib/core-contract-tests/Clarinet.toml
-      - name: Export code coverage
-        id: clarinet_codecov
-        uses: codecov/codecov-action@v3
+
+      ## Upload coverage to codecov
+      ##   - use wretry action, to retry on a failed upload 3x
+      - name: Upload Code Coverage
+        id: code_coverage
+        uses: Wandalen/wretry.action@a163f62ae554a8f3cbe27b23db15b60c0ae2e93c # v1.3.0
         with:
-          files: ./coverage.lcov
-          verbose: true
+          action: codecov/codecov-action@eaaf4bedf32dbdc6b720b63067d99c4d77d6047d # v3.1.4
+          with: |
+            files: ./coverage.lcov
+            fail_ci_if_error: false
+            verbose: true
+          attempt_limit: 3
+          attempt_delay: 10000
